name: geo_dse
channels:
  - conda-forge
dependencies:
  - python=3.9.6
  - jupyter=1.0.0
  - geopandas=0.9.0
  - fiona=1.8.20
  - shapely=1.7.1
  - pyproj=3.1.0
  - six=1.16.0
  - rtree=0.9.7
  - xlrd=2.0.1
  - mapclassify=2.4.3
  - openpyxl=3.0.7
  - seaborn=0.11.2